LIKES_URL = "https://www.instagram.com/your_activity/interactions/likes"

MAX_POSTS_PER_BATCH = 100
WAIT_SECONDS = 20
POST_UNLIKE_DELAY_SECONDS = 5
SELECT_BUTTON_TIMEOUT_SECONDS = 10
MAX_SELECT_REFRESH_RETRIES = 50
MAX_UNLIKE_REFRESH_RETRIES = 50

AUTO_START_ENABLED = True
AUTO_START_POLL_INTERVAL_SECONDS = 1.0
START_READY_BUTTON_TEXT = "Select"
